# PANDAS

In [104]:
import pandas as pd

In [105]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [106]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [107]:
df.describe()

engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          9704.000000    9222.000000  8996.000000     9704.000000   
mean            199.708368       3.962481   149.657292     3001.280993   
std              49.455319       1.999323    29.879555      497.894860   
min              10.000000       0.000000    37.000000      952.681761   
25%             170.000000       3.000000   130.000000     2666.248985   
50%             200.000000       4.000000   149.000000     2993.226296   
75%             230.000000       5.000000   170.000000     3334.957039   
max             380.000000      13.000000   271.000000     4739.077089   

       acceleration   model_year    num_doors  fuel_efficiency_mpg  
count   8774.000000  9704.000000  9202.000000          9704.000000  
mean      15.021928  2011.484027    -0.006412            14.985243  
std        2.510339     6.659808     1.048162             2.556468  
min        6.000000  2000.000000    -4.000000             6.200971  
25%       13.300000  2006.000000    -1.000000            13.267459  
50%       15.000000  2012.000000     0.000000            15.006037  
75%       16.700000  2017.000000     1.000000            16.707965  
max       24.300000  2023.000000     4.000000            25.967222

# NUMPY

In [108]:
import numpy as np

zeros_array = np.zeros(10)
ones_array = np.ones(10)
constant_array = np.full(10, 3)

my_list = [2, 3, 4]
array_from_list = np.array(my_list)
range_array = np.arange(10)
linspace_array = np.linspace(0, 1, 11)

zeros_matrix = np.zeros((5, 2))
ones_matrix = np.ones((5, 2))
constant_matrix = np.full((5, 2), 3)

arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]   # Gets the first column

np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))

arr_1 = arr + 1   # Adds 1 to each element
arr_2 = arr * 2   # Multiplies each element by 2
# Similar operations for division and exponentiation

arr1 = np.ones(4)
arr2 = np.full(4, 3)
result_1 = arr1 + arr2  # Element-wise addition
result_2 = arr1 / arr2  # Element-wise division

arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]

selected_elements = arr[arr > 1]  # Gets elements greater than 1

min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation

In [109]:
std_deviation

np.float64(1.118033988749895)

In [110]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

In [111]:
# addition 
u + v

array([ 5, 11, 13, 12])

In [112]:
# subtraction 
u - v

array([-1,  3, -3,  0])

In [113]:
# scalar multiplication 
2 * v

array([ 6,  8, 16, 12])

In [114]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [115]:
vector_vector_multiplication(u, v)

np.float64(110.0)

In [116]:
u.dot(v)

np.int64(110)

In [117]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [118]:
U = np.array([[2, 7, 5, 6],[3, 4, 8, 6]])
matrix_vector_multiplication(U, v)

array([110., 125.])

In [119]:
U.dot(v)

array([110, 125])

In [120]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [121]:
U = np.array([[2, 7, 1],[3, 4, 2]])     # 3columns and 2rows
V = np.array([[3, 4],[2, 7], [1, 2]])   # 2columns and 3rows
matrix_matrix_multiplication(U, V)

array([[21., 59.],
       [19., 44.]])

In [122]:
U.dot(V)

array([[21, 59],
       [19, 44]])

In [123]:
I = np.eye(2)  # identity matrix
I

array([[1., 0.],
       [0., 1.]])

In [124]:
V

array([[3, 4],
       [2, 7],
       [1, 2]])

In [125]:
V.dot(I)

array([[3., 4.],
       [2., 7.],
       [1., 2.]])

In [126]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])
inv = np.linalg.inv(V)
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [127]:
inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# HOMEWORK

Link: [https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/master/cohorts/2025/01-intro/homework.md]

In [128]:
import pandas as pd

In [129]:
# Q1. Pandas version
pd.__version__

'2.3.1'

In [130]:
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")

In [131]:
df.head(n=5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [132]:
# Q2. Records count
df.shape[0]  # rows count

9704

In [133]:
df.shape[1]  # columns count

11

In [134]:
# Q3. Fuel types
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [135]:
df['fuel_type'].nunique()

2

In [136]:
# Q4. Missing values
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [137]:
# Q5. Max fuel efficiency
df.fuel_efficiency_mpg[df.origin == "Asia"].max()

np.float64(23.759122836520497)

In [138]:
# Q6. Median value of horsepower
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [139]:
df.horsepower.median()

np.float64(149.0)

In [140]:
df.groupby(df.horsepower).horsepower.count().sort_values(ascending=False).head(n=1)

horsepower
152.0    142
Name: horsepower, dtype: int64

In [141]:
df.horsepower = df.horsepower.fillna(152.0)

In [142]:
df.horsepower.median()

np.float64(152.0)

In [143]:
# Q7. Sum of weights
df_asia = df[df.origin == "Asia"]
df_asia.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [144]:
df_asia[['vehicle_weight','model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [145]:
x = np.array(df_asia[['vehicle_weight','model_year']].head(7).values)
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [146]:
xT = x.T
xT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [147]:
XTX = x.dot(xT)
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [148]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.14065606e+08,  5.48536130e+07, -3.76831385e+08,
        -5.99044087e+08,  4.10105044e+08, -7.87026143e+07,
         7.23633092e+07],
       [ 3.29129898e+08,  8.26109025e+08, -3.72548813e+08,
        -7.01583859e+08,  3.27222378e+07, -5.67206124e+07,
        -5.80223502e+07],
       [-6.16516597e+08, -2.64221399e+08,  2.93298395e+08,
         7.94190283e+08, -1.94689452e+08, -1.53391689e+08,
         1.43457519e+08],
       [-4.98522990e+08, -2.71174593e+08,  5.34131775e+08,
         7.89486336e+08, -2.49261495e+08, -2.49261495e+08,
        -5.20318918e+07],
       [-0.00000000e+00, -2.68435456e+08,  2.23517418e-07,
         2.03703699e+08, -2.68435456e+08,  2.68435456e+08,
         6.46082210e+07],
       [ 0.00000000e+00, -1.15043767e+08, -1.15043767e+08,
        -2.70361224e+08,  2.68435456e+08,  2.68435456e+08,
        -3.76263766e+07],
       [ 2.68435456e+08,  3.83479223e+07,  3.83479223e+07,
        -2.12927011e+08,  0.00000000e+00,  0.00000000e+00,
        -1.3225025

In [149]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [152]:
w = xT.dot(XTX_inverse).dot(y)
w

array([ 0.14501345, -0.63631237])

In [153]:
w.sum()

np.float64(-0.4912989164442476)